# Creating a Numpy Array

In [ ]:
import numpy as np
arr=np.array([2,4,56,789])
print(arr)

[  2   4  56 789]


# Common Method in Numpy

In [3]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

1
(4,)
4
int32
4


In [4]:
#Creating a array with specified datatype
ar1=np.array([[3,6],[9,12]],dtype=float)
print(ar1)

[[ 3.  6.]
 [ 9. 12.]]


In [5]:
#Creating a array with all elements zeroes
ar_zero=np.zeros((3,4)) #it create a matrix array with all the elements zeros
print(ar_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#Creating a array with all elements onces
ar_one=np.ones((3,4)) #it create a matrix array with all the elements one
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#Creating a array within a range of elements
ar_range=np.arange(-2,24,4)
print(ar_range)

[-2  2  6 10 14 18 22]


In [8]:
#Creating a array within a range of elements
ar_range=np.arange(-2,24,4)
print(ar_range)

[-2  2  6 10 14 18 22]


In [13]:
#Creating a array with diagonal elements zeros
arr_dia=np.eye(3) # Creates a matrix of 3X3 with diaganol elements 1
print("3X3=",end=" ")
print(arr_dia)

ar_dia=np.eye(3,5) # Creates a matrix of 3X3 with diaganol elements 1
print("3X5=",end=" ")
print(ar_dia)

3X3= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
3X5= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [14]:
#Linspane

ar_lin=np.linspace(0,20,num=8)
print(ar_lin)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [21]:
#Creating a Numpy array with random number
#There are four functions to create a numpy array with random numbers
#1.rand() :-Used to generate a random value between 0 to 1
ar_rand=np.random.rand(6) # generate the 1D array with 6 random values
print(ar_rand)
ar_rand1=np.random.rand(3,5,1) # generate the 3X5 array 
print(ar_rand1)

[0.63098372 0.08109449 0.67316415 0.32603099 0.16996931 0.39262025]
[[[0.84881251]
  [0.45754848]
  [0.5749603 ]
  [0.80172859]
  [0.29734598]]

 [[0.85679788]
  [0.84710895]
  [0.36765872]
  [0.29500611]
  [0.1195948 ]]

 [[0.08563428]
  [0.91635226]
  [0.77914813]
  [0.64446845]
  [0.90004616]]]


In [20]:
#1.rand() :-Used to generate a random value which is close to zero. this may generate numbers
ar_randn=np.random.randn(6) # generate the 1D array with 6 random values
print(ar_randn)
ar_rand1n=np.random.randn(3,5,1) # generate the 3X5 array 
print(ar_rand1n)

[-0.309912    1.06113937  0.93473005 -0.38564566  0.63287776 -0.31214678]
[[[-0.72807126]
  [-0.58187485]
  [ 1.51786228]
  [ 0.16476556]
  [-3.36267762]]

 [[ 1.00803689]
  [-0.13355831]
  [-0.82317626]
  [-1.99886206]
  [-0.63866855]]

 [[ 0.79185815]
  [ 0.96030041]
  [ 1.09286153]
  [-1.52314521]
  [-0.41548543]]]


In [30]:
#1.rand() :-Used to generate a random value which is close to zero. this may generate numbers
ar_randn=np.random.randn(6) # generate the 1D array with 6 random values
print(ar_randn)

ar_rand1n=np.random.randn(3,5,1) # generate the 3X5 array 
print(ar_rand1n)

[-1.42607673 -0.27207147  0.91258141 -1.05377426 -0.76537138 -1.56529463]
[[[ 0.16281834]
  [ 0.35272213]
  [ 0.29126562]
  [ 0.51875179]
  [ 1.60603239]]

 [[ 1.76983581]
  [-0.66118723]
  [-0.65622508]
  [ 0.74039438]
  [ 0.83337743]]

 [[-1.62943448]
  [ 0.04065296]
  [-0.51084253]
  [-0.34513226]
  [-0.23861299]]]


In [31]:
#3.randf() :- used to generate floating numbers within the interval of [0.0 - 1.0]
ar_ranf=np.random.ranf(6) # generate the 1D array with 6 random values
print(ar_ranf)

ar_ranf1=np.random.ranf(3) # generate the 3X5 array 
print(ar_ranf1)

[0.57670846 0.30172587 0.06047116 0.89384302 0.56938643 0.69097601]
[0.73826586 0.35285019 0.33022355]


In [39]:
#4.Randint():-Used to generate random interger within the given range
#Syntax :- randint(min,max,number)
ar_ran=np.random.randint(1,6,7) # generate the 1D array 
print(ar_ran)

[4 4 4 1 2 3 5]


# Shape

In [43]:
ar=np.array([1,2,3,4])
print("Shape of array =",ar.shape)

ar1=np.array([1,2,3,4],ndmin=4)
print("Shape of array2 =",ar.shape)
print("Dimension of array2 =",ar.ndim)

#Reshaping the array or we can say converting the different dimensions arrays to different dimensions arrays
ar2=np.array([1,2,3,4,5,6,7,8])
ar3=ar2.reshape(2,4)
print(ar3)

Shape of array = (4,)
Shape of array2 = (4,)
Dimension of array2 = 1
[[1 2 3 4]
 [5 6 7 8]]
