# Matrix in Numpy

In [5]:
import numpy as np
mat=np.matrix([[1,2],[3,4]])
print(mat)
print("Data Type =",type(mat))

[[1 2]
 [3 4]]
Data Type = <class 'numpy.matrix'>


# Multiplication in Matrix

In [9]:
mat1=np.matrix([[1,2],[3,4]])
mat2=np.matrix([[4,5],[6,7]])
print("Multiplication =\n",mat1*mat2)
print("Using dot() fuction multiplication =\n",mat1.dot(mat2))

Multiplication =
 [[16 19]
 [36 43]]
Using dot() fuction multiplication =
 [[16 19]
 [36 43]]


# Transpose in matrix

In [17]:
print("mat=\n",mat)
print("Transpose of Mat =\n",np.transpose(mat))
print("Transpose with the help of swapaxes() function =\n",np.swapaxes(mat,0,1)) # It changes the axis 0 to 1 

mat=
 [[1 2]
 [3 4]]
Transpose of Mat =
 [[1 3]
 [2 4]]
Transpose with the help of swapaxes() function =
 [[1 3]
 [2 4]]


# Inverse in Matrix

In [14]:
print("Inverse of mat =\n",np.linalg.inv(mat))

Inverse of mat =
 [[-2.   1. ]
 [ 1.5 -0.5]]


# Power

In [16]:
print("Mat in Power of 3 =\n",np.linalg.matrix_power(mat,3))

Mat in Power of 3 =
 [[ 37  54]
 [ 81 118]]


# Determinates

In [19]:
print("Determinates of mat =\t:",np.linalg.det(mat))
print("Determinates of mat1 =\t:",np.linalg.det(mat1))
print("Determinates of mat2 =\t:",np.linalg.det(mat2))
print("Determinates of mat^3 =\t:",np.linalg.det(np.linalg.matrix_power(mat,3)))

Determinates of mat =	: -2.0000000000000004
Determinates of mat1 =	: -2.0000000000000004
Determinates of mat2 =	: -2.000000000000003
Determinates of mat^3 =	: -8.000000000000037
