# Insert and Delete in Numpy Array

In [41]:
import numpy as np
arr=np.array([1,2,3,4,6])
arr=np.append(arr,7)
print("np.append(arr,7) =\t:",arr)  #append method adds the elements in the last
arr=np.insert(arr,4,5)
print("np.insert(arr,4,5) =\t:",arr) #insert method is used the insert the elements at specified index
arr=np.delete(arr,5)
print("np.delete(arr,5) =\t:",arr) #delete the element at the given index
arr=np.delete(arr,(0,2,4,5))
print("np.delete(arr,5) =\t:",arr) #delete the element at the given index's

np.append(arr,7) =	: [1 2 3 4 6 7]
np.insert(arr,4,5) =	: [1 2 3 4 5 6 7]
np.delete(arr,5) =	: [1 2 3 4 5 7]
np.delete(arr,5) =	: [2 4]


# Numpy Functions 

In [79]:
arr1=np.array([1,2,3,4,6])
#Shuffle() Function
np.random.shuffle(arr1) # It shuffle the elements
print("After Shuffing the elements\t:",arr1)

arr2=np.array([1,1,2,3,4,6,7,7,9,22,33])
#UNIQUE() Function
print("np.unique(arr2)\t:",np.unique(arr2)) # It return the unique elements

#Flatten Function
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3.flatten(order="C"))  #Row -major order
print(arr3.flatten(order="F"))  #column - major order
print(arr3.flatten(order="A"))  #column - major order if arr3 is contiguous in memory,row-major order otherwise
print(arr3.flatten(order="K"))  #Array elements in that order which occur in memory

print()
#Ravel Function same as Flatten Function
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.ravel(arr4,order="C"))  #Row -major order
print(np.ravel(arr4,order="F"))  #column - major order
print(np.ravel(arr4,order="A"))  #column - major order if arr3 is contiguous in memory,row-major order otherwise
print(np.ravel(arr4,order="K"))  #Array elements in that order which occur in memory

After Shuffing the elements	: [4 2 6 3 1]
np.unique(arr2)	: [ 1  2  3  4  6  7  9 22 33]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# Copy() & View() methods

In [80]:
co=arr2.copy()
v=arr2.view()
print("Array =\t",arr2)
print("COPIED Variable =\t:",co)
print("VIEWED Variable =\t:",v,"\n")

#changing some elements to arr2
arr2[1]=0
arr2[2]=0

#Viewed and copied variable after changing some elements to arr2
print("Array =\t",arr2)
print("COPIED Variable =\t:",co)
print("VIEWED Variable =\t:",v,"\n")

Array =	 [ 1  1  2  3  4  6  7  7  9 22 33]
COPIED Variable =	: [ 1  1  2  3  4  6  7  7  9 22 33]
VIEWED Variable =	: [ 1  1  2  3  4  6  7  7  9 22 33] 

Array =	 [ 1  0  0  3  4  6  7  7  9 22 33]
COPIED Variable =	: [ 1  1  2  3  4  6  7  7  9 22 33]
VIEWED Variable =	: [ 1  0  0  3  4  6  7  7  9 22 33] 



# Filter Array

In [53]:
arr_5=np.array([1,2,3,4])
f=[True,False,False,True]
new_arr_5=arr_5[f]
print(new_arr_5)

[1 4]


# Concatenation of Array

In [62]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("np.concatenate((arr4,arr5))")
np.concatenate((arr4,arr5))

np.concatenate((arr4,arr5))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [63]:
print("np.concatenate((arr4,arr5)),axis=0")
np.concatenate((arr4,arr5),axis=0)

np.concatenate((arr4,arr5)),axis=0


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [64]:
print("np.concatenate((arr4,arr5)),axis=1")
np.concatenate((arr4,arr5),axis=1)

np.concatenate((arr4,arr5)),axis=1


array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

In [67]:
np.stack((arr4,arr5),axis=0) 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [68]:
np.stack((arr4,arr5),axis=1)

array([[[1, 2, 3],
        [9, 8, 7]],

       [[4, 5, 6],
        [6, 5, 4]],

       [[7, 8, 9],
        [3, 2, 1]]])

In [69]:
np.hstack((arr4,arr5)) #row

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

In [70]:
np.vstack((arr4,arr5)) #colums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [72]:
np.dstack((arr4,arr5)) #height

array([[[1, 9],
        [2, 8],
        [3, 7]],

       [[4, 6],
        [5, 5],
        [6, 4]],

       [[7, 3],
        [8, 2],
        [9, 1]]])

# Splitting of Array

In [77]:
split=np.split(arr4,3)
print(split)
a1,a2,a3=np.split(arr5,3)
print(a1)
print(a2)
print(a3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[9 8 7]]
[[6 5 4]]
[[3 2 1]]


# iteration of Array in Numpy

In [82]:
#there are serval way to iterates the numpy array
#1.like in basic python programming language 
for i in arr:
    print(i) 

1
1
2
3
4
6
7
7
9
22
33
50


In [83]:
# 2.np.nditer(arr)
for i in np.nditer(arr):
    print(i)

1
1
2
3
4
6
7
7
9
22
33
50


In [98]:
# 3.If you want to store the data in the buffer memory while iterating the numpy array.see the following code
for i in np.nditer(arr,flags=['buffered'],op_dtypes=["S"]):
    print(i)


b'1'
b'1'
b'2'
b'3'
b'4'
b'6'
b'7'
b'7'
b'9'
b'22'
b'33'
b'50'



Indexing and Slicing

In [112]:
#Indexing
arr7=np.array([[1,2,3],[3,4,5],[5,6,7],[8,9,7]])
print("arr7[0]=\t:",arr7[0])
print("arr7[0,1]=\t:",arr7[0,1],"\n")

#Slicing
print("arr7[1:]=\t:",arr7[1:],"\n")
print("arr7[:2]=\t:",arr7[:2],"\n")
print("arr7[0:2]=\t:",arr7[0:2],"\n")
print("arr7[::2]=\t:",arr7[::2],"\n")

arr7[0]=	: [1 2 3]
arr7[0,1]=	: 2 

arr7[1:]=	: [[3 4 5]
 [5 6 7]
 [8 9 7]] 

arr7[:2]=	: [[1 2 3]
 [3 4 5]] 

arr7[0:2]=	: [[1 2 3]
 [3 4 5]] 

arr7[::2]=	: [[1 2 3]
 [5 6 7]] 



# Mathematics in Numpy Array
  

In [115]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])
print(ar1+ar2)
print(ar1*ar2)
print(ar1-ar2)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[-4 -4]
 [-4 -4]]


In [120]:
ar=np.array([16,3,32,5,6,225,6,3,245,6,33,2,5,6,3,6,63,2,4])
print("Minimum=\t:",np.min(ar))
print("Maximum=\t:",np.max(ar))
print("Index(Minimum)=\t:",np.argmin(ar))
print("Sin(90)=\t:",np.sin(90))
print("cos(75)=\t:",np.cos(75))
print("cumsum(ar)=\t:",np.cumsum(ar)) #first elements is same as ar second is sum of first and second elements and so on...

Minimum=	: 2
Maximum=	: 245
Index(Minimum)=	: 11
Sin(90)=	: 0.8939966636005579
cos(75)=	: 0.9217512697247493
cumsum(ar)=	: [ 16  19  51  56  62 287 293 296 541 547 580 582 587 593 596 602 665 667
 671]
